[package]
name = "testbed"
version = "0.2.0"
description = "Test projects for structout"
authors = ["resolritter <joao.paulo.silvasouza@hotmail.com>"]
edition = "2018"

[dependencies]
structout = { path = "../.." }

[lib]
name = "testbed"
path = "mod.rs"
