[package]
name = "testbed"
version = "0.1.2"
description = "Tests structout"
authors = ["resolritter <joao.paulo.silvasouza@hotmail.com>"]
edition = "2018"

[dependencies]
structout = { path = "../../.." }

[lib]
name = "testbed"
path = "mod.rs"
